language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: make -C c-figlet CC="$CC" LD="$CC" && make -C c-figlet check

matrix:
  include:
    - os: linux
      compiler: i586-mingw32msvc-gcc
      script: make -C c-figlet CC="$CC" XCFLAGS= LD="$CC"
    - os: linux
      compiler: '"clang -fsanitize=address"'
      script: make -C c-figlet CC="$CC" LD="$CC" && make -C c-figlet check
    - os: linux
      compiler: '"clang -fsanitize=memory"'
      script: make -C c-figlet CC="$CC" LD="$CC" && make -C c-figlet check

